# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ScrollView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ScrollView
	pod 'Material', '3.1.8'
	pod 'IQKeyboardManagerSwift'

  target 'ScrollViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
